name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust_toolchain: [stable, "1.77"]
        exclude:
          - os: windows-latest
            rust_toolchain: "1.77"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.rust_toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_toolchain }}
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose

  build-with-qt:
    strategy:
      matrix:
        qt_version: [5, 6]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build libegl-dev
      - if: ${{ matrix.qt_version == 5 }}
        name: Install Qt 5
        run: sudo apt install qtbase5-dev qttools5-dev qtdeclarative5-dev-tools
      - if: ${{ matrix.qt_version == 6 }}
        name: Install Qt 6
        run: |
          sudo apt install qt6-base-dev qt6-tools-dev qt6-declarative-dev-tools
          sudo ln -s /usr/bin/qmake6 /usr/local/bin/qmake
      - name: Show detected Qt version
        run: make help
      - name: Build release binaries
        run: make release
      - name: Install release binaries
        run: sudo make install
      - name: Build examples
        run: make build-examples

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: qmluic
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install devscripts equivs
          sudo mk-build-deps -i qmluic/contrib/debian/control
      - name: Build deb
        run: make -C qmluic deb
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-deb
          path: qmluic_*.deb
          retention-days: 5

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.77"
          components: clippy
      # TODO: should we switch to actions-rs/clippy-check?
      - name: Lint with clippy
        run: cargo clippy --workspace --all-targets -- -Dwarnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check format
        run: cargo fmt --all --check

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
      - name: Check format
        run: find \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-format -n -Werror --
