name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust_toolchain: [stable, "1.59"]
        exclude:
          - os: windows-latest
            rust_toolchain: "1.59"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust ${{ matrix.rust_toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_toolchain }}
        override: true
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
